apiVersion: v1
kind: Pod
metadata:
  name: CAPI-privileged-pod
  labels:
    name: CAPI-privileged
  namespace: fabriceproject
  annotations:
    openshift.io/scc: privileged
spec:
  containers:
  - name: CAPI-privileged-pod
    image: docker.io/fmoyen/capiapp:latest
    ports:
      - containerPort: 8080
        protocol: TCP
    securityContext:
        privileged: true
  serviceAccount: fabriceproject-service-account
  serviceAccountName: fabriceproject-service-account

