#!/bin/bash

Dir=`ls -d /OCXLSys/devices/pci*/*.1/ocxlfn*.1/ocxl`

echo "LIBOCXL_SYSPATH=$Dir LD_LIBRARY_PATH=/opt/libocxl/obj:$LD_LIBRARY_PATH  /opt/oc-accel/software/tools/oc_maint -v $*"
LIBOCXL_SYSPATH=$Dir LD_LIBRARY_PATH=/opt/libocxl/obj:$LD_LIBRARY_PATH  /opt/oc-accel/software/tools/oc_maint -v $*

