#!/bin/bash
echo "LIBOCXL_SYSPATH=/OCXLSysDevice LD_LIBRARY_PATH=/opt/libocxl/obj:$LD_LIBRARY_PATH  /opt/oc-accel/software/tools/oc_maint -v $*"
LIBOCXL_SYSPATH=/OCXLSysDevice LD_LIBRARY_PATH=/opt/libocxl/obj:$LD_LIBRARY_PATH  /opt/oc-accel/software/tools/oc_maint -v $*
