#!/bin/bash

Card=""

while getopts "C:" option; do
  case $option in
    C)
      Card=$OPTARG
    ;;
  esac
done

Dir=`ls -d /sys/devices/pci*/*.1/ocxlfn*.1/ocxl 2>/dev/null` # Example: /sys/devices/pci0004:00/0004:00:00.1/ocxlfn.0004:00:00.1/ocxl
DirCount=`echo $Dir | wc -w`
IDs=`/usr/local/bin/get_card_id`
IDsCount=`echo $IDs | wc -w`

if [ $IDsCount -eq 0 ]; then
  echo "No OpenCAPI Card detected"
  exit 66
fi

if [ $IDsCount -eq 1 ]; then
  if [[ $# -ne 0  &&  "$*" =~ "-C" ]]; then
    echo "/opt/oc-accel/software/tools/oc_maint -v $*"
    /opt/oc-accel/software/tools/oc_maint -v $*
  else
    echo "/opt/oc-accel/software/tools/oc_maint -v -C$IDs $*"
    /opt/oc-accel/software/tools/oc_maint -v -C$IDs $*
  fi

else
  if [[ $# -ne 0  &&  "$*" =~ "-C" ]]; then
    echo "/opt/oc-accel/software/tools/oc_maint -v $*"
    /opt/oc-accel/software/tools/oc_maint -v $*
  else
    echo "More than one OpenCAPI card detected. Please choose one card with the \"-C\" option (run \"my_oc_find_card\" tool to get the card position)"
    echo -e "Card positions found: \c"
    echo $IDs
  fi
fi
